name: Streamlit App Deployment

on:
  push:
    branches:
      - main

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Streamlit app
      run: |
        export OPENAI_API_KEY=$OPENAI_API_KEY
        streamlit run main.py
